### ISSUE TITLE
The Vdot function does not satisfy negative definite condition

### ISSUE THREAD

**Issue by kimukook** [YaChienChang/Neural-Lyapunov-Control#5]
Hi Ya-Chien,

I tried to run your inverted pendulum case on my own laptop and plot the Lyapunov function and its Lie derivative as shown below:
![NNLF_V](https://user-images.githubusercontent.com/22064903/113354131-8c17a480-92f3-11eb-9c24-26c0b3bd275c.png)
![NNLF_Vdot2](https://user-images.githubusercontent.com/22064903/113354144-9043c200-92f3-11eb-8463-7a02311691e0.png)

There are some regions that Lie derivative of V is positive. Also I found it is pretty weird but I am not sure which part I did it incorrectly, running the same code from Jupiter notebook on my laptop does not show Lyapunov conditions are satisfied from `CheckLyapunov` using `dReal`. Any suggestion on this? Thank you!

**Comment by YaChienChang** [comment]
Hi Muhan Zhao,
Some regions of LieV are positive because the candidate Lyapunov function is not a valid Lyapunov function (it doesn’t pass the verification from dReal). 
I run the inverted pendulum jupyter notebook with dReal: v4.19.02.1 and Pytorch: 1.2.0. The candidate can pass and the LieV plot shown as below:
![Lie](https://user-images.githubusercontent.com/42861335/116945995-e0cd7880-ac2d-11eb-999b-9f78d403be1b.png)
The different versions of the tool might need to use different parameters and iteration to pass the verification. Thank you :)
